<?php
/**
 * @file
 *  AMP integration for the Taboola module.
 */

/**
 * Implements hook_block_view_alter().
 */
function taboola_amp_block_view_alter(&$data, $block) {
  if ($block->module == 'taboola') {
    if (amp_is_amp_request()) {
      $data['content']['#theme'] = 'taboola_amp';
      if (isset($data['content']['#attached'])) {
        unset($data['content']['#attached']);
      }
    }
  }
}

/**
 * Implements hook_theme().
 */
function taboola_amp_theme($existing, $type, $theme, $path) {
  $theme = array(
    'taboola_amp' => array(
      'variables' => array(
        'height' => NULL,
        'width' => NULL,
        'layout' => NULL,
        'heights' => NULL,
        'data_publisher' => NULL,
        'data_mode' => NULL,
        'data_placement' => NULL,
        'data_target_type' => NULL,
        'data_article' => NULL,
      ),
      'template' => 'amp-taboola',
    ),
  );

  return $theme;
}

/**
 * Implements hook_preprocess_taboola_amp().
 */
function taboola_amp_preprocess_taboola_amp(&$variables) {
  $variables['height'] = '100';
  $variables['width'] = '100';
  $variables['layout'] = 'layout';
  $variables['heights'] = 'heights';
  $variables['data_publisher'] = 'data_publisher';
  $variables['data_mode'] = 'data_mode';
  $variables['data_placement'] = 'data_placement';
  $variables['data_target_type'] = 'data_target_type';
  $variables['data_article'] = 'data_article';
}

