<?php
/**
 * @file
 *  AMP integration for the Taboola module.
 */
require_once ('taboola_amp.admin.inc');

/**
 * Implements hook_block_view_alter().
 */
function taboola_amp_block_view_alter(&$data, $block) {
  if ($block->module == 'taboola') {
    if (amp_is_amp_request()) {
      $data['content']['#theme'] = 'taboola_amp';
      if (isset($data['content']['#attached'])) {
        unset($data['content']['#attached']);
      }
      $block_index = taboola_get_block_array_index($block->delta);
      // Hard coded values. Can be added to config if needed.
      $data['content']['#height'] = '100';
      $data['content']['#width'] = '100';
      $data['content']['#layout'] = 'responsive';
      $data['content']['#article'] = 'auto';
      // These values come from configuration.
      $data['content']['#publisher'] = taboola_get_setting('taboola_publisher');
      $data['content']['#heights'] = taboola_get_block_setting($block_index, 'amp_heights');
      $data['content']['#mode'] = taboola_get_block_setting($block_index, 'mode');
      $data['content']['#placement'] = taboola_get_block_setting($block_index, 'placement');
      $data['content']['#target_type'] = taboola_get_block_setting($block_index, 'target_type');
    }
  }
}

/**
 * Implements hook_theme().
 */
function taboola_amp_theme($existing, $type, $theme, $path) {
  $theme = array(
    'taboola_amp' => array(
      'variables' => array(
        'delta' => '',
        'height' => NULL,
        'width' => NULL,
        'layout' => NULL,
        'heights' => NULL,
        'publisher' => NULL,
        'mode' => NULL,
        'placement' => NULL,
        'target_type' => NULL,
        'article' => NULL,
      ),
      'template' => 'taboola-amp',
    ),
  );

  return $theme;
}
